name: Bygg og deploy master til S3
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  build_target_folder: build
  project_folder: .
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13]
    outputs:
      build_artifact: ${{ env.build_target_folder }}
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        id: "setup-node-js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ${{ env.project_folder }}
        run: npm ci --legacy-peer-deps
      - name: Run unit tests
        working-directory: ${{ env.project_folder }}
        run: CI=true npm run test
      - name: Build
        working-directory: ${{ env.project_folder }}
        run: |
          BUILD_PATH=${{ env.build_target_folder }} npm run build
      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_target_folder }}
          path: ${{ env.build_target_folder }}
  terraform:
    runs-on: ubuntu-latest
    needs: test-and-build
    defaults:
      run:
        working-directory: tf
    permissions:
      id-token: write
      contents: read
    env:
      # Artifact name is the same as the build folder
      TF_VAR_BUILD_FOLDER: ${{ needs.test-and-build.outputs.build_artifact }}

    steps:
      - name: Check out this repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.test-and-build.outputs.build_artifact }}
          path: ${{ needs.test-and-build.outputs.build_artifact }}
      - name: Configure the AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/deploy-dorthe-obf-csv-transform
      - name: Use Terraform github actions
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "~> 1.1.4"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=10s
